---
- name: Install tor packages
  apt:
    name: "{{ item }}"
  with_items:
    - deb.torproject.org-keyring
    - tor
    - torsocks
    - tor-arm

- name: setup torsocks to accept inbound connections
  lineinfile:
    path: /etc/tor/torsocks.conf
    line: "AllowInbound 1"

- name: enable tor service
  systemd:
    name: tor
    enabled: yes
    masked: no
    state: started
  when: not in_docker
