- name: Install ecryptfs
  apt:
    name: ecryptfs-utils

- name: Configure system to load the ecryptfs modules
  lineinfile:
    path: /etc/modules
    line: ecryptfs
    create: yes

- name: Load the ecryptfs module
  when: not dockerenv.stat.exists
  modprobe:
    name: ecryptfs
