.\"   Man page for hashbang
.TH man 7 "29 May 2014" "0.5" "#! man page"

.SH NAME
#! \- "shell" service and collective of awesome people.

.SH SYNOPSIS

bash <(curl hashbang.sh)

.SH DESCRIPTION

We are a diverse community of people who love teaching and learning.
Putting a #! at the beginning of a "script" style program tells a computer that
it needs to "do something" or "execute" the file. Likewise, we are a community
of people that like to "do stuff".

If you like technology and want to learn to write your first program, learn to
use Linux, or even take on interesting challenges with some of the best in
the industry, you are in the right place.
.SH EXAMPLES
.TP

.BI ssh\ someuser@hashbang.sh
Use the "ssh" command to get yourself back into your account from any computer
that has your private key.
.TP
.BI cat\ foo
echo the foo file to the console

.SH AVAILABLE SOFTWARE
.SS Compilers / Interpreters / Programming Languages
perl - A high-level, general-purpose dynamic programming language.  Commonly
referred to as "the duct tape of the internet."

python - A high-level, general-purpose programming language that emphasizes
code readability.

ruby - A dynamic, object-oriented general-purpose programming language.

haskell - A standardized, general-purpose programming language with non-strict
semantics and strong static typing.

lua - A lightweight multi-paradigm programming language designed as a scripting
language.

clojure - A general-purpose programmign language with an emphasis on functional
programming.  It is a dialect of the Lisp programming language.

go - A statically-typed language developed at Google with syntax loosely derived from C with
garbage collection.

nodejs - A cross-platform runtime environment for server-side and network
applications written in javascript.

sbcl - (Steel Bank Common Lisp) A Lisp implementation that features a high
performance native compiler, Unicode support, and threading.

ghc - (The Glorious Glasgow Haskell Compilation System) a native code compiler
for Haskell.

gcc - (GNU Compiler Collection) A compiler system that supports C, C++ and
various other programming languages.

smlnj -(Standard ML of New Jersey) a compiler and programming environment for
Standard ML

spidermonkey - JavaScript engine maintained by the Mozilla Foundation.
.SS Text Editors
vim - A popular vi clone and the IDE of choice of most of the #! regulars.
Ships by default on all operating systems that matter.

emacs - A very capable scriptable text editor also capable of being a full IDE
with all the power of vim implemented in different ways. Not in as wide of
use as it once was but plenty of skilled hackers still swear by it.

nano - A text editor that emulates the Pico text editor and is part of the GNU
Project.

joe - (Joe's Own Editor) a text editor designed for ease of use.

pico - (Pine Composer) a text editor originally integrated wtih the pine e-mail
client and designed at the Office of Computing and Communications at the
University of Washington.

e3 - A full-featured text editor with choosable syntax including Pico, Emacs,
and VI.

ne - (nice editor) A text editor created at the University of Milan intended to
be an alternative to VI for beginners.

mcedit - Internal text editor for the Midnight Commander file manager.

zile - An Emacs like text editor that is less resource intensive.

mg - (originally MicroGnuEmacs) An editor similar to Emacs with a smaller
memory footprint and faster speed.

jed - A text editor that makes use of the S-Lang library.
.SS Password Management
pass - A shell based password manager.
.SS Cryptography / Hashing
encfs - A FUSE-based cryptographic filesystem that transparently encrypts files
using an arbitrary directory as storage for the encrypted files.

gpg - (GNU Privacy Guard) A GPL Licensed alternative to the PGP suite of
cryptographic software compliant with RFC 4880.

md5sum - Calculates and verifies 128-bit MD5 hashes as described in RFC 1321.

shasum - Calculates and verifies SHA hashes.

bcrypt - A key derivation function for passwords based on the Blowfish cipher.

ccrypt - A utility for the secure encryption and decryption of files and
streams.
.SS Time Management
calcurse - A calendar and scheduling application used to keep track of events,
appointments, and everyday tasks.

calendar - Checks current directory or CALENDAR_DIR environment variable for a
file named calendar and displays appointments and reminders.

remind - A sophisticated reminder service.

wyrd - A text-based front-end to the Remind program.

taskwarrior - a CLI time and task management tool.

tudu - A command-line tool to manage TODO lists hierarchically.
.SS Shells
bash - (Bourne Again Shell) The standard shell on most Linux and unix-like
systems which is a GNU replacement for the Unix Bourne shell.  A linux classic
brah.

zsh - (Z Shell)  An extension of the Bourne shell extended with features from
ksh and tcsh.

fish - (Friendly Interactive Shell) An attempt to maek a more interactive,
user-friendly shell.

ksh - (Korn Shell) A shell backwards compatible with the Bourne shell but also
includes many features of the C shell.
.SS Email
mutt - A text-based email client.  "All mail clients suck.  This one just sucks
less."

alpine - (Alternatively Licensed Program for Internet News and Email) A
text-based email client developed at the University of Washington.

slrn - A text-based news client that uses the S-Lang library.

offlineimap - An IMAP synchronization utility software, capable of
synchronizing mail on IMAP server with local Maildir folder or another server.

mu - A set of tools that enable you to quickly find e-mails you are looking
for in Maildir.
.SS Math
ledger - A double-entry accounting system accessed from the command line.
units - Unit conversion utility.
dc - A reverse-polish desk calculator which supports arbitrary-precision
arithmetic.
qalc - A small simple to use command-line calculator.
bc - An arbitrary precision calculator language
.SS Chat / IM
weechat-curses - Wee Enhanced Environment for Chat (Curses version)

irssi - A text-based IRC client written in the C programming language.

centerim - A text based menu and window-driven instant messaging interface that
supports ICQ, Yahoo!, AIM, MSN, IRC, XMPP, LiveJournal, and Gadu-Gadu
protocols.

finch - A console-based instant messaging client based on the libpurple
library.

bitlbee - Bitlbee brings Instant Messaging to IRC clients. It has support for 
multiple IM networks/protocols including Google Talk.

.RS
To use bitlbee in weechat enter
.RS
.B
/server add bitlbee irc.hashbang.sh/6610
.RE
then
.RS
.B
/connect bitlbee 
.RE
this will force join you into the 
.B
&bitlbee
channel. If you are interested in using Google Talk follow this guide 
http://wiki.bitlbee.org/HowtoGtalk
.RE

barnowl - A curses-based instant messaging client forked from teh ktools owl
project that supports Zephyr, AIM, Jabber, IRC, and Twitter.

pork - An ncurses-based AOL instant messanger and IRC client.

scrollz - An advanced ircII-based IRC client.

ii - A minimalistic FIFO and filesystem based IRC client.

sic - A fast, simple IRC client that reads from standard input and prints
server output to standard output.

erc - An IRC client integrated into GNU Emacs.
.SS News Reader
newsbeuter - A text-based news aggregator that supports  RSS and Atom.

rsstail - An RSS news reader which works similar to the tail command.

canto - An ncurses RSS reader built to be flexible on top of python.

rawdog - (RSS Aggregator Without Delusions Of Grandeur) An RSS aggregator that
uses the Python feedparser module to retrieve articles from feeds in RSS, Atom
and other formats.
.SS Web Browsing
links - A menu-driven text mode web browser with ncurses interface supporting colors, table
rendering and background downloading.

elinks - Similar to lniks, but also supports Form Input, Password Management,
and Tabbed Browsing

lynx - A general purpose distributed information web browser.

w3m - A text based web browser and pager.

html2text - Reads an HTML document and outputs plain text characters.
.SS Database
sqlite3 - A relational database management system contained in a C programming
library.

mariadb - A fork of the MySQL relational database management system led by the
original developer of MySQL.

postgresql - An Object-relational database management system that emphasises
extensibility and standards-compliance.

mongodb - A document-oriented NoSQL database that usesJSON-like documents with
dynamic schemas.

redis - A networked, in-memory, key-value data store with optional durability
written in ANSI C.
.SS File Management
mc -

scp -

rsync -

rsynccrypto -

duplicity -

vifm -

ranger -

du -

ncdu -

find -

locate -

tree -
.SS Archiving
atool -

zip -

unzip -

p7zip -

tar -

dar -

gzip -

zpaq -
.SS Network
iptraf -

nethogs -

slurm -

nmap -

ngrep -

tcpdump -

trickle -

ifstat -

iftop -

mtr -

telnet -

netpipes -

ssh -

siege -

lftp -

curl -

rtorrent -

aria2 -

ipcalc -

socat -

netcat -

ssh-copy-id -

zeromq -

rabbitmq -
.SS Image Tools
optipng -

imagemagick -

gd -
.SS Code Management
cvs -

svn -

mercurial -

git -

tig -

cloc -

diff -

vimdiff -

vimpager -

hub -

ctags -

cmake -
.SS Games/Toys

zangband -

nethack -

slashem -

cmatrix -

frotz -

bsdgames -

bb -

sl -

bastet -

greed -

gnugo -

gnuchess -

gnushcgi -

moon-buggy -

typespeed -
.SS MUSH/MOO/MUD Clients

tinyfunge -

tintin -

kbtin -

pennmush -
.SS System Management Utilities
bonnie++ -

htop -

dstat -

iotop -

sysdig -

strace -

cpulimit -

cgroups -
.SS Window/Session Managers

tmux -

screen -

dtach -

byobu -

.SS Misc. / Unsorted (Sort these!)
pv -

ttyrec - 

tsung - 

xargs - 

parallel - 

tpp - 

ack - 

ag - 

repl - 

watch - 

libev - 

libevent - 

lame - 

cowsay - 

dos2unix - 

unix2dos - 
.SH HISTORY

2004 - lrvick secured free-for-all usage of a dedicated server, hosted at
"The Planet" datacenter in Austin, TX, in exchange for providing free system
administration services to an educational web application provider. He
distributed shell accounts to a group of friends for personal projects,
organizing resources and efforts via IRC.

2006 - Having outgrown the shared server, the community opted to invest in our
own dedicated server, lovingly named "Adam". All projects were migrated over,
and a few months later "Eve" was added for redundancy and to minimize downtime.
These were hosted at SiteGenie in Rochester, MN.

2008 - As a hosting service, we hosted many web projects visited by hundreds of
thousands of users, in addition to seeing hundreds of users on our IRC and
shell services. Our community was known in multiple IRC circles to have very
well-developed overall system security, and we regularly dealt with various
types of attacks trying to break through. A "Script Kiddie" named Piratox,
unable to break in through any usual methods, opted to make use of a large
botnet, disrupting us with a large scale DDOS attack.

The attack was significant enough that the entire SiteGenie datacenter was
taken offline. Though we tracked down Piratox and ended the dispute, SiteGenie
was unprepared to deal with the possibility of further DDOS attacks of similar
scale and promptly ended our contract. They generously offered to overnight our
hard drives to any location we chose. Seeing the potential in this, we involved
it in the backup plans that had already been set in motion.

Echelon, a volunteer admin, brought "Noah" online in his Ohio basement.
Bluescales, another volunteer admin, rushed to setup a VPS in a Montana
Datacenter. He dubbed it "Moses". We quickly routed essential services from
backups between the two servers while one of the two backup drives containing
user files was overnighted to Noah. Shell user files were available to our
community again within 24 hours.

With emergency options in place, we sought a new primary server. After
reviewing our budget and options, we opted for a dedicated server at a newer
company, VolumeDrive, in Wilkes Barre, Pennsylvania. We took a chance on them
due to their reputation for inexpensive, unmetered bandwidth plans with
regular bandwidth testing. "Melchiz" was born, and quickly became responsible
for community services including shells, email, and IRC, as well as hosting
most smaller websites.

VolumeDrive was a good fit for most of our services; however, like SiteGenie, 
they were unwilling to deal with the unwanted attention that our historical
reputation could bring. To address this, we deployed "Samson" in an undisclosed
location, ensuring it would be difficult to target by disruptive parties.
"Gideon" was deployed in Germany as a dumb proxy to more reliably protect
Samson's location. Were it to ever go down, more could rapidly take its place.
We felt really good about the maintainability of this setup.

2010 - Samson needed a kernel update to address security issues that had
recently come to light. One of our volunteer admins, Viaken, decided to take on
the kernel update on his own, but did not include the correct SATA driver. On
reboot, Samson experienced a kernel panic. Per a special agreement with the
datacenter, hosting was available and free so long as support was never
contacted. Thus, Samson was to remain frozen at a kernel panic screen, and
may still be hung there to this day. Gideon, now purposeless, was taken
offline shortly thereafter.

We were left with no choice but to risk hosting all services on Melchiz until
a better solution could be secured.

2013 - After frequent downtime and multiple disputes with VolumeDrive
(including a case where they mistakenly formatted one of our production hard
drives), our community sought to "go big or go home". We went big and secured
the dedicated server "Og". Og's specs were more than overkill for everything
we provided, but we knew it would be worth it for our long-term goals of
expanding our free community offerings to the general public. 

2014 - #! shells are now available to the general public. Welcome!


.SH You can help!

Fork, make changes, and submit Github Pull Requests Here:

https://github.com/lrvick/hashbang.shi

This man file can be updated here:

https://github.com/lrvick/hashbang.sh/blob/master/usr/local/man/man7/hashbang.7
