.\"Manpage for hashbang
.TH man 7 "29 May 2014" "0.5" "#! man page"

.SH NAME
#! \- "shell" service and collective of awesome people.

.SH SYNOPSIS

bash <(curl hashbang.sh)

.SH DESCRIPTION

We are a diverse community of people who love teaching and learning.
Putting a #! at the beginning of a "script" style program tells a computer that
it needs to "do something" or "execute" the file. Likewise, we are a community
of people that like to "do stuff".

If you like technology and want to learn to write your first program, learn to
use Linux, or even take on interesting challenges with some of the best in
the industry, you are in the right place.
.SH EXAMPLES
.TP

.BI ssh\ someuser@hashbang.sh
Use the "ssh" command to get yourself back into your account from any computer
that has your private key.
.TP
.BI cat\ foo
echo the foo file to the console

.SH AVAILABLE SOFTWARE
.SS Compilers / Interpreters / Programming Languages
perl -

python -

ruby - 

haskell -

lua - 

clojure -

go -

nodejs -

sbcl -

ghc -

gcc -

smlnj -

spidermonkey -
.SS Text Editors
vim - A popular vi clone and the IDE of choice of most of the #! regulars.
Ships by default on all operating systems that matter.

emacs - A very capable scriptable text editor also capable of being a full IDE
with all the power of vim implemented in different ways. Not in as wide of
use as it once was but plenty of skilled hackers still swear by it.

nano -

joe -

pico -

nano -

joe -

pico -

e3 -

ne -

mcedit -

zile -

mg -

jed -
.SS Password Management
pass - 
.SS Cryptography / Hashing
encfs -

gpg -

md5sum -

shasum -

bcrypt -

ccrypt -
.SS Time Management
calcurse -

calendar -

remind -

wyrd -

taskwarrier -

tudu -
.SS Shells
bash -

zsh -

fish -

ksh -
.SS Email
mutt -

alpine -

slrn -

offlineimap -

mu -
.SS Math
ledger -
units -
dc -
qalc -
bc -
.SS Chat / IM
weechat-curses -

irssi -

centerim -

finch -

bitlbee -

barnowl -

pork -

scrollz -

ii -

sic -

erc -
.SS News Reader
newsbeuter -

rsstail -

canto -

rawdog -
.SS Web Browsing
links -

elinks -

lynx -

w3m -

html2text -
.SS Database
sqlite3 -

mariadb -

postresql -

mongodb -

redis -
.SS File Management
mc -

scp -

rsync -

rsynccrypto -

duplicity -

vifm -

ranger -

du -

ncdu -

find -

locate -

tree -
.SS Archiving
atool -

zip -

unzip -

p7zip -

tar -

dar -

gzip -

zpaq -
.SS Network
iptraf -

nethogs -

slurm -

nmap -

ngrep -

tcpdump -

trickle -

ifstat -

iftop -

mtr -

telnet -

netpipes -

ssh -

siege -

lftp -

curl -

rtorrent -

aria2 -

ipcalc -

socat -

netcat -

ssh-copy-id -

zeromq -

rabbitmq -
.SS Image Tools
optipng -

imagemagick -

gd -
.SS Code Management
cvs -

svn -

mercurial -

git -

tig -

cloc -

diff -

vimdiff -

vimpager -

hub -

ctags -

cmake -
.SS Games/Toys

zangband -

nethack -

slashem -

cmatrix -

frotz -

bsdgames -

bb -

sl -

bastet -

greed -

gnugo -

gnuchess -

gnushcgi -

moon-buggy -

typespeed -
.SS MUSH/MOO/MUD Clients

tinyfunge -

tintin -

kbtin -

pennmush -
.SS System Management Utilities
bonnie++ -

htop -

dstat -

iotop -

sysdig -

strace -

cpulimit -

cgroups -
.SS Window/Session Managers

tmux -

screen -

dtach -

byobu -

.SS Misc. / Unsorted (Sort these!)
pv -

ttyrec - 

tsung - 

xargs - 

parallel - 

tpp - 

ack - 

ag - 

repl - 

watch - 

libev - 

libevent - 

lame - 

cowsay - 

dos2unix - 

unix2dos - 
.SH HISTORY

2004 - lrvick secured free-for-all usage of a dedicated server, hosted at
"The Planet" datacenter in Austin, TX, in exchange for providing free system
administration services to an educational web application provider. He
distributed shell accounts to a group of friends for personal projects,
organizing resources and efforts via IRC.

2006 - Having outgrown the shared server, the community opted to invest in our
own dedicated server, lovingly named "Adam". All projects were migrated over,
and a few months later "Eve" was added for redundancy and to minimize downtime.
These were hosted at SiteGenie in Rochester, MN.

2008 - As a hosting service, we hosted many web projects visited by hundreds of
thousands of users, in addition to seeing hundreds of users on our IRC and
shell services. Our community was known in multiple IRC circles to have very
well-developed overall system security, and we regularly dealt with various
types of attacks trying to break through. A "Script Kiddie" named Piratox,
unable to break in through any usual methods, opted to make use of a large
botnet, disrupting us with a large scale DDOS attack.

The attack was significant enough that the entire SiteGenie datacenter was
taken offline. Though we tracked down Piratox and ended the dispute, SiteGenie
was unprepared to deal with the possibility of further DDOS attacks of similar
scale and promptly ended our contract. They generously offered to overnight our
hard drives to any location we chose. Seeing the potential in this, we involved
it in the backup plans that had already been set in motion.

Echelon, a volunteer admin, brought "Noah" online in his Ohio basement.
Bluescales, another volunteer admin, rushed to setup a VPS in a Montana
Datacenter. He dubbed it "Moses". We quickly routed essential services from
backups between the two servers while one of the two backup drives containing
user files was overnighted to Noah. Shell user files were available to our
community again within 24 hours.

With emergency options in place, we sought a new primary server. After
reviewing our budget and options, we opted for a dedicated server at a newer
company, VolumeDrive, in Wilkes Barre, Pennsylvania. We took a chance on them
due to their reputation for inexpensive, unmetered bandwidth plans with
regular bandwidth testing. "Melchiz" was born, and quickly became responsible
for community services including shells, email, and IRC, as well as hosting
most smaller websites.

VolumeDrive was a good fit for most of our services; however, like SiteGenie, 
they were unwilling to deal with the unwanted attention that our historical
reputation could bring. To address this, we deployed "Samson" in an undisclosed
location, ensuring it would be difficult to target by disruptive parties.
"Gideon" was deployed in Germany as a dumb proxy to more reliably protect
Samson's location. Were it to ever go down, more could rapidly take its place.
We felt really good about the maintainability of this setup.

2010 - Samson needed a kernel update to address security issues that had
recently come to light. One of our volunteer admins, Viaken, decided to take on
the kernel update on his own, but did not include the correct SATA driver. On
reboot, Samson experienced a kernel panic. Per a special agreement with the
datacenter, hosting was available and free so long as support was never
contacted. Thus, Samson was to remain frozen at a kernel panic screen, and
may still be hung there to this day. Gideon, now purposeless, was taken
offline shortly thereafter.

We were left with no choice but to risk hosting all services on Melchiz until
a better solution could be secured.

2013 - After frequent downtime and multiple disputes with VolumeDrive
(including a case where they mistakenly formatted one of our production hard
drives), our community sought to "go big or go home". We went big and secured
the dedicated server "Og". Og's specs were more than overkill for everything
we provided, but we knew it would be worth it for our long-term goals of
expanding our free community offerings to the general public. 

2014 - #! shells are now available to the general public. Welcome!

.SH TODO
.SS Update this file
Lots of fun short terminal examples under EXAMPLES.

TLDR descriptions for all available software.

Continue description with list of general things we provide to users like web 
hosting, irc services, personal email, community project collaboration. Be
creative.

.SS Other stuff 
working user@hashbang.sh MX records for getting real email to shells

man hashbang man page with list of all commands and common things

error handling on provisor

come up with method for users to set passwords for themselves

benchmarking 

how many users with tmux sessions connected to irc can we handle?

Implement 20k/s bandwidth limit for all free users

Implement 5gb storage space limit or all free users

implement 256m memory limit for all free users

spruce up tmux status line for new users (What should we put in it?)

update docs to tell people how to get back to their shell, and back to non irc
tab.

installer should make alias to get back in

.SS You can help!

Fork, make changes, and submit Github Pull Requests Here:

https://github.com/lrvick/hashbang.shi

This man file can be updated here:

https://github.com/lrvick/hashbang.sh/blob/master/usr/local/man/man7/hashbang.7
