.\"Manpage for hashbang
.TH man 7 "29 May 2014" "0.5" "#! man page"

.SH NAME
#! \- "shell" service and collective of awesome people.

.SH SYNOPSIS

bash <(curl hashbang.sh)

.SH DESCRIPTION

We are a diverse community of people who love teaching and learning.
Putting a #! at the beginning of a "script" style program tells a computer that
it needs to "do something" or "execute" the file. Likewise, we are a community
of people that like to "do stuff".

If you like technology and want to learn to write your first program, learn to
use Linux, or even take on interesting challenges with some of the best in
the industry, you are in the right place.

.SH EXAMPLES

.SH FILES

.SH HISTORY

2004 - lrvick secured free-for-all usage of a dedicated server, hosted at
"The Planet" datacenter in Austin, TX, in exchange for providing free system
administration services to an educational web application provider. He
distributed shell accounts to a group of friends for personal projects,
organizing resources and efforts via IRC.

2006 - Having outgrown the shared server, the community opted to invest in our
own dedicated server, lovingly named "Adam". All projects were migrated over,
and a few months later "Eve" was added for redundancy and to minimize downtime.
These were hosted at SiteGenie in Rochester, MN.

2008 - As a hosting service, we hosted many web projects visited by hundreds of
thousands of users, in addition to seeing hundreds of users on our IRC and
shell services. Our community was known in multiple IRC circles to have very
well-developed overall system security, and we regularly dealt with various
types of attacks trying to break through. A "Script Kiddie" named Piratox,
unable to break in through any usual methods, opted to make use of a large
botnet, disrupting us with a large scale DDOS attack.

The attack was significant enough that the entire SiteGenie datacenter was
taken offline. Though we tracked down Piratox and ended the dispute, SiteGenie
was unprepared to deal with the possibility of further DDOS attacks of similar
scale and promptly ended our contract. They generously offered to overnight our
hard drives to any location we chose. Seeing the potential in this, we involved
it in the backup plans that had already been set in motion.

Echelon, a volunteer admin, brought "Noah" online in his Ohio basement.
Bluescale, another volunteer admin, rushed to setup a VPS in a Montana
Datacenter. He dubbed it "Moses". We quickly routed essential services from
backups between the two servers while one of the two backup drives containing
user files was overnighted to Noah. Shell user files were available to our
community again within 24 hours.

With emergency options in place, we sought a new primary server. After
reviewing our budget and options, we opted for a dedicated server at a newer
company, VolumeDrive, in Wilkes Barre, Pennsylvania. We took a chance on them
due to their reputation for inexpensive, unmetered bandwidth plans with
regular bandwidth testing. "Melchiz" was born, and quickly became responsible
for community services including shells, email, and IRC, as well as hosting
most smaller websites.

VolumeDrive was a good fit for most of our services; however, like SiteGenie, 
they were unwilling to deal with the unwanted attention that our historical
reputation could bring. To address this, we deployed "Samson" in anundisclosed
location, ensuring it would be difficult to target by disruptive parties.
"Gideon" was deployed in Germany as a dumb proxy to more reliably protect
Samson's location. Were it to ever go down, more could rapidly take its place.
We felt really good about the maintainability of this setup.

2010 - Samson needed a kernel update to address security issues that had
recently come to light. One of our volunteer admins, Viaken, decided to take on
the kernel update on his own, but did not include the correct SATA driver. On
reboot, Samson experienced a kernel panic. Per a special agreement with the
datacenter, hosting was available and free so long as support was never
contacted. Thus, Samson was to remain frozen at a kernel panic screen, and
may still be hung there to this day. Gideon, now purposeless, was taken
offline shortly thereafter.

We were left with no choice but to risk hosting all services on Melchiz until
a better solution could be secured.

2013 - After frequent downtime and multiple disputes with VolumeDrive
(including a case where they mistakenly formatted one of our production hard
drives), our community sought to "go big or go home". We went big and secured
the dedicated server "Og". Og's specs were more than overkill for everything
we provided, but we knew it would be worth it for our long-term goals of
expanding our free community offerings to the general public. 

2014 - #! shells are now available to the general public. Welcome!
