---
- hosts: all
  tasks:

  - name: Configure ssh to use sss for authorized-keys
    blockinfile:
      path: /etc/sshd_config
      block: |
        AuthorizedKeysFile        none
        AuthorizedKeysCommand     /usr/bin/sss_ssh_authorizedkeys
        AuthorizedKeysCommandUser nobody

  - name: Configure sssd to use custom ldap server
    blockinfile:
      path: /etc/sssd/sssd.conf
      block: |
        [sssd]
        domains = HASHBANG
        services = nss, pam, ssh
        config_file_version = 2

        [nss]


        [domain/HASHBANG]
        enumerate = TRUE
        id_provider = ldap
        access_provider = ldap
        ldap_uri = ldaps://ldap.hashbang.sh
        ldap_search_base = dc=hashbang,dc=sh
        ldap_tls_reqcert = demand
        ldap_user_search_base = ou=People,dc=hashbang,dc=sh
        ldap_user_ssh_public_key = sshPublicKey
        ldap_pwd_policy = none
        ldap_access_order = host
        ldap_user_authorized_host = host
        cache_credentials = true

        [pam]
        id_provider = proxy

  - name: Update Nsswitch to not use sss for sudoers
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: "^sudoers:"
      line: "sudoers:        files"

  - name: Update pam to use sss
    block:
    - name: update pam common-account to use sss
      copy:
        dest: /etc/pam.d/common-account
        content: |
          account	required	  pam_nologin.so
          account	sufficient	pam_sss.so
          account	sufficient	pam_unix.so
          account	sufficient	pam_localuser.so
          account	required	  pam_deny.so

    - name: update pam common-auth to use sss
      copy:
        dest: /etc/pam.d/common-auth
        content: |
          auth	sufficient  pam_sss.so
          auth	sufficient  pam_unix.so use_first_pass
          auth	required		pam_deny.so

    - name: Update pam common-password to use sss
      copy:
        dest: /etc/pam.d/common-password
        content: |
          password  requisite	  pam_pwquality.so retry=3
          password  sufficient  pam_sss.so use_authtok
          password  sufficient  pam_unix.so obscure use_authtok try_first_pass sha512
          password requisite	 pam_deny.so

    - name: Update pam common-session to use sss
      copy:
        dest: /etc/pam.d/common-session
        content: |
          session	substack	common-session-noninteractive
          session	optional	pam_mkhomedir.so
          session	optional	pam_umask.so      usergroups

    - name: Update pam common-session-noninteractive to use sss
      copy:
        dest: /etc/pam.d/common-session-noninteractive
        content: |
          session	required	  pam_env.so
          session	required	  pam_namespace.so  unmnt_remnt
          session	required	  pam_limits.so
          session	required	  pam_systemd.so
          session	required	  pam_exec.so       type=open_session /etc/security/limits.sh
          session	sufficient	pam_sss.so
          session	sufficient	pam_unix.so
          session	required	 pam_deny.so

  - name: Update pam adt to use common-session-interactive as substack
    lineinfile:
      path: /etc/pam.d/adt
      regexp: "^@include common-session-noninteractive"
      line: "session    substack   common-session-noninteractive"

  - name: Update pam cron to use common-session-interactive as substack
    lineinfile:
      path: /etc/pam.d/cron
      regexp: "^@include common-session-noninteractive"
      line: "session    substack   common-session-noninteractive"

  - name: Update pam sudo to use common-session-interactive as substack
    lineinfile:
      path: /etc/pam.d/sudo
      regexp: "^@include common-session-noninteractive"
      line: "session    substack   common-session-noninteractive"

  - name: Setup NSLCD to ldap hashbang settings
    copy:
      dest: /etc/nslcd.conf
      content: |
        uid nslcd
        gid nslcd

        uri ldaps://ldap.hashbang.sh/

        base dc=hashbang,dc=sh

        tls_reqcert never
        tls_cacertfile /etc/ssl/certs/ca-certificates.crt
