---
- hosts: all
  tasks:

  - name: Install basic packages needed for Ansible
    apt:
      name: apt-transport-https

  - apt_key:
      keyserver: keys.gnupg.net
      id: 11E9DE8848F2B65222AA75B8D1820DB22A11534E

  - apt_repository:
      repo: deb https://weechat.org/debian stretch main
      state: present

  - apt_repository:
      repo: deb-src https://weechat.org/debian stretch main
      state: present

  - name: Update apt repositories
    apt:
      update_cache: yes

  - name: Install all system packages
    apt:
      name: "{{ item }}"
    with_items:
      - apt-transport-https
      - acl
      - acpi
      - acpi-support-base
      - acpid
      - adduser
      - aglfn
      - alpine
      - ansible
      - apt
      - apt-file
      - apt-transport-https
      - apt-utils
      - aptitude
      - aptitude-common
      - aria2
      - aspell
      - aspell-en
      - at
      - atool
      - auditd
      - autoconf
      - automake
      - autopoint
      - autotools-dev
      - base-files
      - base-passwd
      - bash
      - bash-completion
      - bastet
      - bc
      - bcrypt
      - binfmt-support
      - binutils
      - bitlbee
      - bitlbee-common
      - bsdgames
      - bsdmainutils
      - bsdutils
      - build-essential
      - busybox
      - byobu
      - bzip2
      - ca-certificates
      - cgroup-tools
      - checkpolicy
      - cloc
      - cloud-initramfs-dyn-netconf
      - cloud-initramfs-growroot
      - cloud-utils
      - cmake
      - cmake-data
      - command-not-found
      - console-setup
      - console-setup-linux
      - coreutils
      - cowsay
      - cpio
      - cpp
      - cracklib-runtime
      - cron
      - curl
      - cvs
      - dash
      - dbus
      - dbus-x11
      - dc
      - dconf-gsettings-backend
      - dconf-service
      - dctrl-tools
      - debconf
      - debconf-i18n
      - debconf-utils
      - debhelper
      - debian-archive-keyring
      - debian-keyring
      - debianutils
      - debsums
      - devscripts
      - dh-lua
      - dh-python
      - dictionaries-common
      - diffutils
      - dirmngr
      - discount
      - discover
      - discover-data
      - distro-info
      - distro-info-data
      - dmidecode
      - dmsetup
      - dns-root-data
      - dnsutils
      - docutils-common
      - dos2unix
      - dpkg
      - dpkg-dev
      - duplicity
      - e2fslibs
      - e2fsprogs
      - eject
      - elinks
      - elinks-data
      - emacs-nox
      - emacs24-bin-common
      - emacs24-common
      - emacs24-common-non-dfsg
      - emacs24-nox
      - emacsen-common
      - encfs
      - erlang-asn1
      - erlang-base
      - erlang-crypto
      - erlang-inets
      - erlang-mnesia
      - erlang-os-mon
      - erlang-public-key
      - erlang-runtime-tools
      - erlang-snmp
      - erlang-ssl
      - euca2ools
      - exuberant-ctags
      - fakeroot
      - ferm
      - figlet
      - file
      - findutils
      - firejail
      - fish
      - fish-common
      - fontconfig
      - fontconfig-config
      - fonts-dejavu-core
      - fonts-lyx
      - frotz
      - fuse
      - g++
      - gawk
      - gcc
      - gconf-service
      - gconf2
      - gconf2-common
      - gdb
      - geoip-database
      - gettext
      - gettext-base
      - gforth
      - gforth-common
      - gforth-lib
      - ghc
      - gir1.2-glib-2.0
      - git
      - git-email
      - git-man
      - glances
      - glib-networking
      - glib-networking-common
      - glib-networking-services
      - gnuchess
      - gnugo
      - gnupg
      - gnupg-agent
      - gnupg2
      - gnuplot-data
      - gnuplot-nox
      - golang-go
      - golang-src
      - gpgv
      - grep
      - groff-base
      - grub-common
      - grub-pc
      - grub-pc-bin
      - grub2-common
      - gsettings-desktop-schemas
      - gsfonts
      - guile-2.0
      - guile-2.0-dev
      - guile-2.0-libs
      - gyp
      - gzip
      - haveged
      - hddtemp
      - hostname
      - html2text
      - htop
      - httpie
      - iamerican
      - ibritish
      - ieee-data
      - ienglish-common
      - ifupdown
      - imagemagick
      - imagemagick-6.q16
      - imagemagick-common
      - info
      - init
      - init-system-helpers
      - initramfs-tools
      - initscripts
      - insserv
      - install-info
      - installation-report
      - intltool-debian
      - iotop
      - ipcalc
      - iperf
      - iproute
      - iproute2
      - iptables
      - iputils-ping
      - ipxe-qemu
      - irssi
      - isc-dhcp-client
      - isc-dhcp-common
      - iso-codes
      - ispell
      - java-common
      - javascript-common
      - joe
      - john
      - john-data
      - jq
      - kbd
      - kexec-tools
      - keyboard-configuration
      - klibc-utils
      - kmod
      - krb5-locales
      - ksh
      - ldap-utils
      - ldnsutils
      - less
      - lftp
      - linux-image-amd64
      - lm-sensors
      - locales
      - locales-all
      - locate
      - login
      - logrotate
      - lsb-base
      - lsb-release
      - lsof
      - ltrace
      - lua5.1
      - lua5.2
      - lua5.3
      - luajit
      - luarocks
      - lynx
      - lynx-cur
      - m4
      - man-db
      - manpages
      - manpages-dev
      - mat
      - mawk
      - mc
      - mc-data
      - mime-support
      - mksh
      - mlock
      - mosh
      - mount
      - msmtp
      - mtr
      - multiarch-support
      - mutt
      - mysql-common
      - nano
      - ncdu
      - ncurses-base
      - ncurses-bin
      - ncurses-doc
      - ncurses-term
      - net-tools
      - netbase
      - netcat-traditional
      - nethack-common
      - nethack-console
      - nfacct
      - nmap
      - node-abbrev
      - node-ansi
      - node-ansi-color-table
      - node-archy
      - node-async
      - node-block-stream
      - node-combined-stream
      - node-cookie-jar
      - node-delayed-stream
      - node-forever-agent
      - node-form-data
      - node-fstream
      - node-fstream-ignore
      - node-github-url-from-git
      - node-glob
      - node-graceful-fs
      - node-gyp
      - node-inherits
      - node-ini
      - node-json-stringify-safe
      - node-lockfile
      - node-lru-cache
      - node-mime
      - node-minimatch
      - node-mkdirp
      - node-mute-stream
      - node-node-uuid
      - node-nopt
      - node-normalize-package-data
      - node-npmlog
      - node-once
      - node-osenv
      - node-qs
      - node-read
      - node-read-package-json
      - node-request
      - node-retry
      - node-rimraf
      - node-semver
      - node-sha
      - node-sigmund
      - node-slide
      - node-tar
      - node-tunnel-agent
      - node-underscore
      - node-which
      - nodejs
      - nodejs-dev
      - nodejs-legacy
      - nscd
      - nslcd
      - nslcd-utils
      - oidentd
      - openbios-ppc
      - openbios-sparc
      - openhackware
      - openntpd
      - openssh-client
      - openssh-server
      - openssh-sftp-server
      - openssl
      - os-prober
      - p7zip
      - pandoc
      - pandoc-data
      - parallel
      - parted
      - pass
      - passwd
      - patch
      - pciutils
      - pep8
      - perl
      - perl-base
      - perl-modules
      - php-cgi
      - php-cli
      - php-common
      - php-curl
      - php-fpm
      - php-json
      - php-mysql
      - php-sqlite3
      - pidgin-data
      - pinentry-curses
      - pkg-config
      - po-debconf
      - policykit-1
      - poppler-data
      - postfix
      - procmail
      - procps
      - psmisc
      - pv
      - pwgen
      - pyflakes
      - python
      - python-apt
      - python-apt-common
      - python-audit
      - python-backports.ssl-match-hostname
      - python-boto
      - python-cffi
      - python-characteristic
      - python-chardet
      - python-cheetah
      - python-colorama
      - python-configobj
      - python-crypto
      - python-cryptography
      - python-dateutil
      - python-debian
      - python-debianbts
      - python-decorator
      - python-defusedxml
      - python-dev
      - python-distlib
      - python-distro-info
      - python-docutils
      - python-ecdsa
      - python-flake8
      - python-gdbm
      - python-geoip
      - python-gi
      - python-hachoir-core
      - python-hachoir-parser
      - python-html5lib
      - python-httplib2
      - python-ipy
      - python-jinja2
      - python-json-pointer
      - python-jsonpatch
      - python-ldap
      - python-lockfile
      - python-lxml
      - python-markupsafe
      - python-matplotlib-data
      - python-mccabe
      - python-minimal
      - python-mock
      - python-mutagen
      - python-ndg-httpsclient
      - python-netaddr
      - python-networkx
      - python-newt
      - python-nose
      - python-numpy
      - python-oauth
      - python-openssl
      - python-paramiko
      - python-pdfrw
      - python-pip
      - python-pkg-resources
      - python-ply
      - python-potr
      - python-prettytable
      - python-pyasn1
      - python-pyasn1-modules
      - python-pycparser
      - python-pygments
      - python-pyparsing
      - python-reportlab
      - python-reportlab-accel
      - python-requestbuilder
      - python-requests
      - python-roman
      - python-serial
      - python-service-identity
      - python-setuptools
      - python-six
      - python-soappy
      - python-sss
      - python-stevedore
      - python-talloc
      - python-tox
      - python-twisted
      - python-twisted-bin
      - python-twisted-conch
      - python-twisted-core
      - python-twisted-mail
      - python-twisted-names
      - python-twisted-news
      - python-twisted-runner
      - python-twisted-web
      - python-twisted-words
      - python-tz
      - python-urllib3
      - python-virtualenv
      - python-websocket
      - python-wheel
      - python-wstools
      - python-yaml
      - python-zope.interface
      - python2.7
      - python2.7-dev
      - python2.7-minimal
      - python3
      - python3-apt
      - python3-bottle
      - python3-chardet
      - python3-colorama
      - python3-crypto
      - python3-decorator
      - python3-dev
      - python3-distlib
      - python3-html5lib
      - python3-jinja2
      - python3-markupsafe
      - python3-minimal
      - python3-numpy
      - python3-pip
      - python3-pkg-resources
      - python3-psutil
      - python3-py
      - python3-pyasn1
      - python3-pysnmp4
      - python3-reportbug
      - python3-requests
      - python3-scipy
      - python3-setuptools
      - python3-six
      - python3-software-properties
      - python3-urllib3
      - python3-venv
      - python3-virtualenv
      - python3-wheel
      - qalc
      - qemu-slof
      - qemu-system-common
      - qemu-user
      - qemu-utils
      - qprint
      - qtcore4-l10n
      - ranger
      - readline-common
      - redis-server
      - redis-tools
      - remind
      - reportbug
      - reptyr
      - resolvconf
      - rsync
      - rsyslog
      - rtorrent
      - ruby
      - rubygems-integration
      - samba-libs
      - sbcl
      - screen
      - seabios
      - sed
      - sensible-utils
      - sgml-base
      - shared-mime-info
      - shellcheck
      - siege
      - signing-party
      - silversearcher-ag
      - silversearcher-ag-el
      - slashem
      - slashem-common
      - socat
      - sqlite3
      - ssh
      - ssl-cert
      - sssd
      - sssd-ad
      - sssd-ad-common
      - sssd-common
      - sssd-ipa
      - sssd-krb5
      - sssd-krb5-common
      - sssd-ldap
      - sssd-proxy
      - sssd-tools
      - startpar
      - stow
      - strace
      - subversion
      - sudo
      - swaks
      - sysstat
      - tar
      - task-english
      - tasksel
      - tasksel-data
      - tcl
      - tcl-tls
      - tcl8.5
      - tcl8.6
      - tcllib
      - tcpd
      - telnet
      - tig
      - tmux
      - toilet
      - toilet-fonts
      - topgit
      - traceroute
      - tree
      - tudu
      - tzdata
      - ucf
      - udev
      - unattended-upgrades
      - unbound
      - unbound-anchor
      - units
      - unzip
      - urlview
      - usbutils
      - util-linux
      - util-linux-locales
      - vim-common
      - vim-nox
      - vim-runtime
      - vim-tiny
      - virtualenv
      - virtualenv-clone
      - virtualenvwrapper
      - w3m
      - wamerican
      - weechat
      - weechat-core
      - weechat-curses
      - weechat-lua
      - weechat-plugins
      - weechat-perl
      - weechat-python
      - wget
      - whiptail
      - whois
      - wyrd
      - xauth
      - xdg-user-dirs
      - xkb-data
      - xml-core
      - xz-utils
      - zangband-data
      - zile
      - zip
      - zlib1g
      - zlib1g-dev
      - znc
      - zpaq
      - zsh
      - zsh-common
